"""
OceanGuard — FastAPI API Endpoints
====================================
SIH PS 26143 | NTRO
"""

import time
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional
from fastapi import APIRouter, UploadFile, File, Form, Query, HTTPException

from app.schemas.models import (
    HealthResponse, DetectionResponse, AttributionResponse,
    SpillDetection, Alert, AlertAckRequest, PipelineRequest, PipelineResponse
)
from app.ml.inference import SARInferenceEngine
from app.ml.ais_correlator import AISCorrelator
from app.data.ais_generator import generate_synthetic_ais_scenario

router = APIRouter(prefix="/api")

# ─── GLOBAL SINGLETONS ────────────────────────────────────────────────────────

inference_engine = SARInferenceEngine()
correlator = AISCorrelator()

# Paths to AIS demo data
DATA_DIR        = Path(__file__).parent.parent / "data" / "sample_data"
SAMPLE_AIS_CSV  = DATA_DIR / "synthetic_ais.csv"
SAMPLE_AIS_JSON = DATA_DIR / "ais_scenario.json"

# Auto-generate synthetic AIS demo data if missing
if not SAMPLE_AIS_CSV.exists() or not SAMPLE_AIS_JSON.exists():
    print("⚡ Pre-generating synthetic AIS demo dataset...")
    spill_time = datetime(2024, 11, 14, 8, 51, 0, tzinfo=timezone.utc)
    generate_synthetic_ais_scenario(
        spill_lat=14.5204, spill_lon=76.3210,
        spill_timestamp=spill_time,
        output_dir=DATA_DIR
    )

# Load AIS tracks AND vessel metadata from the generated JSON
if SAMPLE_AIS_CSV.exists():
    correlator.load_ais_data(SAMPLE_AIS_CSV)

# Bug #6 fix: populate vessel_meta from the rich JSON generated by ais_generator
# so attributes like name/type/flag/owner are returned correctly by correlator.
if SAMPLE_AIS_JSON.exists():
    import json
    with open(SAMPLE_AIS_JSON) as _f:
        _scenario = json.load(_f)
    for _v in _scenario.get("vessels", []):
        correlator.vessel_meta[_v["mmsi"]] = {
            "imo":       _v.get("imo", ""),
            "name":      _v.get("name", ""),
            "type":      _v.get("type", "Unknown Vessel"),
            "flag":      _v.get("flag", "Unknown"),
            "flag_code": _v.get("flag_code", "XX"),
            "dwt":       _v.get("dwt", 0),
            "call_sign": _v.get("call_sign", ""),
            "owner":     _v.get("owner", "Unknown"),
            "last_port": _v.get("last_port", "Unknown"),
            "destination": _v.get("destination", "Unknown"),
        }
    print(f"✅ Vessel metadata loaded for {len(correlator.vessel_meta)} vessels")

START_TIME = time.time()

# In-memory alert store
ALERTS_STORE: List[Alert] = [
    Alert(
        id="ALT-1001",
        type="critical",
        title="New Oil Spill Detected",
        message="SAR analysis detected 12.4 km² spill in Bay of Bengal (94.7% confidence)",
        timestamp="2024-11-14T08:51:00Z",
        spill_id="SPILL-2024-001"
    ),
    Alert(
        id="ALT-1002",
        type="high",
        title="AIS Gap Detected — Suspicious",
        message="MV KALPANA CHAWLA went AIS dark for 47 min near spill origin",
        timestamp="2024-11-14T08:55:00Z",
        spill_id="SPILL-2024-001",
        vessel_id="419000123"
    ),
    Alert(
        id="ALT-1003",
        type="medium",
        title="Palk Strait Spill — Monitoring",
        message="5.8 km² spill in Palk Strait (87.3% confidence). Drift trajectory stable.",
        timestamp="2024-11-14T08:15:00Z",
        spill_id="SPILL-2024-002"
    )
]


# ─── SHARED LOGIC (reusable by both HTTP routes and internal pipeline calls) ──

def _run_sar_detection(lat: float, lon: float, file_path: Optional[Path] = None) -> SpillDetection:
    """Core SAR detection logic — used by both /detect endpoint and pipeline."""
    spill_data = inference_engine.predict_image(file_path, center_lat=lat, center_lon=lon)
    spill = SpillDetection(**spill_data)

    # Immediately run attribution to populate suspects list
    if correlator.indexed:
        spill_time = datetime.fromisoformat(spill.timestamp.replace("Z", "+00:00"))
        attrs = correlator.attribute(spill.center[0], spill.center[1], spill_time, spill.id)
        if attrs:
            spill.suspects = [a["mmsi"] for a in attrs[:3]]
            spill.top_vessel_confidence = attrs[0]["attribution_score"]
    return spill


def _run_attribution(spill_id: str, lat: float, lon: float, timestamp: str) -> AttributionResponse:
    """Core attribution logic — used by both /attribution endpoint and pipeline."""
    t_start = time.time()
    try:
        spill_time = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
    except ValueError:
        spill_time = datetime.now(timezone.utc)

    attributed = correlator.attribute(lat, lon, spill_time, spill_id)
    proc_time  = round((time.time() - t_start) * 1000, 2)

    return AttributionResponse(
        spill_id=spill_id,
        vessels=attributed,
        total_candidates_evaluated=len(correlator.tracks),
        processing_time_ms=proc_time
    )


# ─── HEALTH ──────────────────────────────────────────────────────────────────

@router.get("/health", response_model=HealthResponse)
async def health_check():
    """System health check endpoint."""
    return HealthResponse(
        status="online",
        model_loaded=inference_engine.is_loaded,
        ais_records_indexed=len(correlator.tracks),
        active_spills=3,
        uptime_seconds=round(time.time() - START_TIME, 1)
    )


# ─── SAR DETECTION ───────────────────────────────────────────────────────────

@router.post("/detect", response_model=DetectionResponse)
async def detect_oil_spill(
    file: Optional[UploadFile] = File(None),
    lat: float = Form(14.5204),
    lon: float = Form(76.3210),
    demo_mode: bool = Form(True)
):
    """
    POST /api/detect
    Upload a Sentinel-1 SAR GeoTIFF or trigger demo prediction.
    """
    try:
        temp_path = None
        if file and not demo_mode:
            # Save upload to temp file (Windows-safe path)
            temp_dir = Path(__file__).parent.parent.parent / "tmp"
            temp_dir.mkdir(exist_ok=True)
            temp_path = temp_dir / (file.filename or "upload.tiff")
            contents = await file.read()
            temp_path.write_bytes(contents)

        spill = _run_sar_detection(lat, lon, file_path=temp_path)

        if temp_path and temp_path.exists():
            temp_path.unlink()

        return DetectionResponse(
            success=True,
            spill=spill,
            message="SAR segmentation successfully completed.",
            processing_steps=[
                "Sentinel-1 GeoTIFF Ingestion",
                "Lee Speckle Filtering (7×7 window)",
                "Sigma-nought dB Normalization [-30 to 0 dB]",
                "U-Net Segmentation Pass (FP16 AMP)",
                "Contour Extraction & Georeferencing"
            ]
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Inference error: {str(e)}")


# ─── AIS ATTRIBUTION ─────────────────────────────────────────────────────────

@router.get("/attribution/{spill_id}", response_model=AttributionResponse)
async def get_vessel_attribution(
    spill_id: str,
    lat:       float = Query(14.5204),
    lon:       float = Query(76.3210),
    timestamp: str   = Query("2024-11-14T08:51:00Z")
):
    """
    GET /api/attribution/{spill_id}
    Runs weighted multi-factor AIS vessel attribution for a detected spill.
    """
    return _run_attribution(spill_id, lat, lon, timestamp)


# ─── ALERTS ──────────────────────────────────────────────────────────────────

@router.get("/alerts", response_model=List[Alert])
async def get_alerts():
    return ALERTS_STORE


@router.post("/alerts/ack")
async def acknowledge_alerts(req: AlertAckRequest):
    for alert in ALERTS_STORE:
        if alert.id in req.alert_ids:
            alert.acknowledged = True
    return {"success": True, "acknowledged_count": len(req.alert_ids)}


# ─── END-TO-END PIPELINE DEMO ────────────────────────────────────────────────

@router.post("/pipeline/run", response_model=PipelineResponse)
async def run_full_pipeline(req: PipelineRequest):
    """
    POST /api/pipeline/run
    Full pipeline: SAR Detect → AIS Attribute → Generate Alert
    Bug #5 fix: calls shared helper functions instead of route functions directly.
    """
    t_start       = time.time()
    lat, lon      = 14.5204, 76.3210
    spill_time_str = req.spill_timestamp or "2024-11-14T08:51:00Z"

    # Step 1: SAR detection via shared helper (not the HTTP handler)
    spill = _run_sar_detection(lat, lon, file_path=None)

    # Step 2: AIS attribution via shared helper
    attr_res = _run_attribution(spill.id, lat, lon, spill_time_str)

    # Step 3: Auto-generate alert
    if attr_res.vessels:
        top = attr_res.vessels[0]
        new_alert = Alert(
            id=f"ALT-{int(time.time())}",
            type="critical" if top.attribution_score > 80 else "high",
            title=f"Spill Attribution: {top.name}",
            message=(
                f"{top.name} ({top.flag}) identified as primary suspect "
                f"({top.attribution_score:.0f}% confidence) for {spill.id}."
            ),
            timestamp=datetime.now(timezone.utc).isoformat(),
            spill_id=spill.id,
            vessel_id=top.mmsi
        )
        ALERTS_STORE.insert(0, new_alert)

    total_time = round((time.time() - t_start) * 1000, 1)

    return PipelineResponse(
        success=True,
        spill=spill,
        attribution=attr_res,
        alerts_generated=1 if attr_res.vessels else 0,
        total_time_ms=total_time,
        message="End-to-end intelligence pipeline executed successfully."
    )
